# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RLOsFGAYmasCaB-dVJ472RWbKSGbG8Pk
"""

!pip install geopandas
import geopandas as gpd
import matplotlib.pyplot as plt

map_df = gpd.read_file("england_parl_2011.shp")
# map_df is a Pandas dataframe
f, ax = plt.subplots(1, figsize=(6, 6))
ax = map_df.plot(ax=ax)
ax.set_axis_off()

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import random
# %matplotlib inline
plt.style.use('ggplot')

people1 = pd.read_csv('england_parl_2011.csv')
people1 = people1.set_index('code')
people2 = pd.read_csv('HoC-2017-copy.csv')
people2 = people2.set_index('code')
#people3 = pd.concat([people1,people2], ignore_index=True)
#people3

df_joined = people1.merge(people2, left_index=True, right_index=True)
df_joined

#df_joined = df_joined.column["percentage"] = 100 * ["majority"] / ["electorate"]

map_df
map_df = map_df.set_index('code')
df2 = map_df.merge(df_joined, left_index=True, right_index=True)
df2

f, ax = plt.subplots(1, figsize=(10, 10))
ax = df2.plot(ax=ax, column='lab')
ax.set_axis_off()